services:
  web:
    build: .
    container_name: elmosliga-web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/Elmosliga
    command: python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
